### PR TITLE
Grammar updates

### PR DESCRIPTION
**Pull request by gameshamilton**
Minor grammar updates

### CODE REVIEW

**Comment by funkhouserw** [comment]
@gameshamilton I see someone else had the same idea!  

I just rebased my PR #3 with your changes.  You can close this PR so that @jbaggett only needs to interact with #3 to get both your and my changes.

**Comment by gameshamilton** [comment]
Very clever! I'll have to learn to rebase someday. Thanks again Wilson.

**Comment by jbaggett** [comment]
You're both beyond me, I'm a github novice!

**Comment by funkhouserw** [comment]
@jbaggett in that case let me know if you want any help or have any questions -- github and I are fast friends.

**Comment by DataScienceUWL** [comment]
I'm working on it!  I'll reach out if I can't figure it out.

**Pull request closed without merging**
